/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package android.framework;

import java.awt.Dimension;
import javax.swing.JPanel;
import org.netbeans.api.visual.widget.ComponentWidget;
import org.netbeans.api.visual.widget.Scene;

/**
 * This class manages a single screen which is initially generated as well as generated by adding a button. 
 * 
 * @author shoaib ahmed
 */
public class MobileScreen {
    private JPanel screen;
    private String screenTitle;
    private ComponentWidget widget;

    /**
     * This is the default constructor, which generates a Mobile Screen on UI.
     * 
     * @param title The title of the Mobile Screen.
     * @param scene The scene in which screen is made.
     */
    public MobileScreen(String title,Scene scene) {
        screen = new JPanel();
        screenTitle = title;
        widget = new ComponentWidget(scene, screen);
    }
    
    /**
     * Sets the size of mobile screen.
     * 
     * @param width Width of the screen.
     * @param height Height of the screen
     */
    public void setScreenSize(int width, int height){
        screen.setPreferredSize(new Dimension(width, height));
    }
    
    /**
     * Set position of mobile screen.
     * 
     * @param x Value of x-axis.
     * @param y Value of y-axis.
     */
    public void setScreenPosition(int x, int y){
       screen.setBounds(x, y, screen.getWidth(), screen.getHeight());
    }
    
    /**
     * Returns the Component Widget.
     * 
     * @return Component Widget.
     */
    public ComponentWidget getWidget(){
        return widget;
    }
    
    
    
}
